global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'file_writer_metrics'
    static_configs:
      - targets: ['localhost:19090']

  - job_name: 'file_reader_metrics'
    static_configs:
      - targets: ['localhost:29090']
